# Assignment A_02 - NumPy Tutorial
Topics covered:

- NumPy
- Arrays
- Array Indexing
- Data Types
- Array Math
- Broadcasting


In [1]:
import numpy as np

# 1. Arrays

In [2]:
a = np.array([1, 2, 3])

print(a)
print(type(a))
print(a.shape)

print(a[0], a[1], a[2])

a[0] = 5
print(a)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [3]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(b)
print("Shape:", b.shape)

print(b[0, 0])
print(b[0, 1])
print(b[1, 0])

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
1
2
4


In [4]:
a = np.zeros((2, 2))
print("Zeros:")
print(a)

b = np.ones((1, 2))
print("\nOnes:")
print(b)

c = np.full((2, 2), 7)
print("\nFull:")
print(c)

d = np.eye(2)
print("\nIdentity Matrix:")
print(d)

e = np.random.random((2, 2))
print("\nRandom:")
print(e)

Zeros:
[[0. 0.]
 [0. 0.]]

Ones:
[[1. 1.]]

Full:
[[7 7]
 [7 7]]

Identity Matrix:
[[1. 0.]
 [0. 1.]]

Random:
[[0.79248738 0.20976648]
 [0.54989585 0.93108363]]


# 2. Array Indexing

In [5]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original Array:")
print(a)

b = a[:2, 1:3]

print("\nSliced Array:")
print(b)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array:
[[2 3]
 [6 7]]


In [6]:
print("Before:", a[0, 1])

b[0, 0] = 77

print("After:", a[0, 1])
print(a)

Before: 2
After: 77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Integer array indexing

In [7]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(a[0, 0])
print(a[1, 1])
print(a[2, 0])

1
4
5


# Boolean array indexing

In [8]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

bool_index = a > 2

print("Boolean Array:")
print(bool_index)

print("\nValues greater than 2:")
print(a[bool_index])

Boolean Array:
[[False False]
 [ True  True]
 [ True  True]]

Values greater than 2:
[3 4 5 6]


In [9]:
print(a[a > 2])

[3 4 5 6]


# 3. Data Types

In [10]:
import numpy as np

x = np.array([1, 2])   
print(x.dtype)         

x = np.array([1.0, 2.0])   
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64)   
print(x.dtype) 

int64
float64
int64


# 4. Array Math

In [11]:
x = np.array([
    [1, 2],
    [3, 4]
], dtype=np.float64)

y = np.array([
    [5, 6],
    [7, 8]
], dtype=np.float64)

print("x:")
print(x)

print("\ny:")
print(y)

x:
[[1. 2.]
 [3. 4.]]

y:
[[5. 6.]
 [7. 8.]]


# Now, Lets do ;
Addition
Subtraction 
Multiplication 
Division
Square root

In [12]:
print(x + y)
print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [13]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [14]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [15]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [16]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


# Dot product

In [17]:
v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

219
219


# Sum operations

In [18]:
x = np.array([
    [1, 2],
    [3, 4]
])

print("Total sum:", np.sum(x))
print("Column sums:", np.sum(x, axis=0))
print("Row sums:", np.sum(x, axis=1))

Total sum: 10
Column sums: [4 6]
Row sums: [3 7]


# Transpose

In [19]:
print("Original:")
print(x)

print("\nTranspose:")
print(x.T)

Original:
[[1 2]
 [3 4]]

Transpose:
[[1 3]
 [2 4]]


# 5. Broadcasting

In [20]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

v = np.array([1, 0, 1])

y = x + v

print("Original Matrix:")
print(x)

print("\nVector:")
print(v)

print("\nBroadcasting Result:")
print(y)

Original Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector:
[1 0 1]

Broadcasting Result:
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [21]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

result = a + b

print("Array a:")
print(a)

print("\nArray b:")
print(b)

print("\nResult:")
print(result)

Array a:
[[1 2 3]
 [4 5 6]]

Array b:
[10 20 30]

Result:
[[11 22 33]
 [14 25 36]]
